// Auto-generated database types from Supabase
// This file will be regenerated by the pre-commit hook

export type Database = {
  public: {
    Tables: {
      // Tables will be defined here after creating migrations
    }
    Views: {
      // Views will be defined here
    }
    Functions: {
      // Functions will be defined here
    }
    Enums: {
      // Enums will be defined here
    }
    CompositeTypes: {
      // Composite types will be defined here
    }
  }
}